collections:
  essay:
    sort_by: order
    output: true
defaults:
- scope:
    path: ''
    type: essay
  values:
    layout: essay-content
    permalink: /essay/:slug:output_ext
url: https://dcnb.github.io
baseurl: /frankenstein
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv
title: 'Lord Lister No. 0040: De valsche spoorwegdief'
author: Matull, Kurt, 1872-1920
tagline: null
description: 'A digital edition of Lord Lister No. 0040: De valsche spoorwegdief by
  Matull, Kurt, 1872-1920, extracted from Project Gutenberg'
keywords: digital humanities; multimodal essays; lib-static
exhibit-creator: dcnb
metadata: demo-compoundobjects-metadata
organization-name: Center for Digital Inquiry and Learning (CDIL)
organization-link: https://cdil.lib.uidaho.edu/
organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png
exclude:
- docs/
- Rakefile
- rakelib/
- README.md
- LICENSE
- CITATION.cff
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
sass:
  style: compressed
