collections:
  essay:
    sort_by: order
    output: true
defaults:
- scope:
    path: ''
    type: essay
  values:
    layout: essay-content
    permalink: /essay/:slug:output_ext
url: https://dcnb.github.io
baseurl: /frankenstein
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv
title: Pride and Prejudice
author: Austen, Jane, 1775-1817
tagline: null
description: A digital edition of Pride and Prejudice by Austen, Jane, 1775-1817,
  extracted from Project Gutenberg
keywords: digital humanities; multimodal essays; lib-static
exhibit-creator: dcnb
metadata: demo-compoundobjects-metadata
organization-name: Center for Digital Inquiry and Learning (CDIL)
organization-link: https://cdil.lib.uidaho.edu/
organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png
exclude:
- docs/
- Rakefile
- rakelib/
- README.md
- LICENSE
- CITATION.cff
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
sass:
  style: compressed
